/**
 * AUTO-GENERATED CONFIGURATION
 * Do not edit this file directly. Use .env instead.
 */

export const CONFIG = {
    // API Server (Go Backend)
    API_BASE_URL: 'http://localhost:8081',
    WS_BASE_URL: 'ws://localhost:8081',

    // Web Portal (NextJS/Frontend)
    PORTAL_BASE_URL: 'http://localhost:8081',

    // Default Settings
    DEFAULT_MODEL: 'base',
    CHUNK_DURATION_MS: 5000,
};
