export const MESSAGE_TYPES = {
  START_RECORDING: 'START_RECORDING',
  STOP_RECORDING: 'STOP_RECORDING',
  VOLUME_UPDATE: 'VOLUME_UPDATE',
  TRANSCRIPT_UPDATE: 'TRANSCRIPT_UPDATE',
  RECORDING_ERROR: 'RECORDING_ERROR',
  RECORDING_WARNING: 'RECORDING_WARNING'
};

export const STORAGE_KEYS = {
  IS_RECORDING: 'isRecording',
  RECORDING_TAB: 'recordingTab',
  ACCESS_TOKEN: 'accessToken',
  USER_INFO: 'userInfo'
};
