import os

def sync_env():
    env_path = '.env'
    config_path = 'extension/shared/config.js'
    
    # Mặc định
    config = {
        'API_URL': 'http://localhost:8081',
        'WEB_URL': 'http://localhost:8080'
    }
    
    # Đọc file .env
    if os.path.exists(env_path):
        with open(env_path, 'r') as f:
            for line in f:
                if '=' in line and not line.startswith('#'):
                    key, value = line.strip().split('=', 1)
                    if key in config:
                        config[key] = value
    
    # Tạo nội dung cho config.js
    content = f"""/**
 * AUTO-GENERATED CONFIGURATION
 * Do not edit this file directly. Use .env instead.
 */

export const CONFIG = {{
    // API Server (Go Backend)
    API_BASE_URL: '{config['API_URL']}',
    WS_BASE_URL: '{config['API_URL'].replace('http', 'ws')}',
    
    // Web Portal (NextJS/Frontend)
    PORTAL_BASE_URL: '{config['WEB_URL']}',
    
    // Default Settings
    DEFAULT_MODEL: 'base',
    CHUNK_DURATION_MS: 5000,
}};
"""
    
    # Ghi file
    os.makedirs(os.path.dirname(config_path), exist_ok=True)
    with open(config_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"✅ [Scriberr] Config synced: {config['API_URL']} | {config['WEB_URL']}")

if __name__ == "__main__":
    sync_env()
